### ISSUE TITLE
plasticc preprocessing issue

### ISSUE THREAD

**Issue by raphaelshirley** [kboone/avocado#3] opened 2019-11-12 18:59 UTC
Hi,

I'm getting the following error when preprocessing the plasticc data set. Any ideas?

Best,

Raphael.

(test) mps017431:plasticc rs548$ avocado_download_plasticc
Downloading the PLAsTiCC dataset from zenodo...

Skipping note1_dataRelease.pdf, already exists.
Skipping note2_modelNames.pdf, already exists.
Skipping plasticc_modelpar.tar.gz, already exists.
Skipping plasticc_test_lightcurves_01.csv.gz, already exists.
Skipping plasticc_test_lightcurves_02.csv.gz, already exists.
Skipping plasticc_test_lightcurves_03.csv.gz, already exists.
Skipping plasticc_test_lightcurves_04.csv.gz, already exists.
Skipping plasticc_test_lightcurves_05.csv.gz, already exists.
Skipping plasticc_test_lightcurves_06.csv.gz, already exists.
Skipping plasticc_test_lightcurves_07.csv.gz, already exists.
Skipping plasticc_test_lightcurves_08.csv.gz, already exists.
Skipping plasticc_test_lightcurves_09.csv.gz, already exists.
Skipping plasticc_test_lightcurves_10.csv.gz, already exists.
Skipping plasticc_test_lightcurves_11.csv.gz, already exists.
Skipping plasticc_test_metadata.csv.gz, already exists.
Skipping plasticc_train_lightcurves.csv.gz, already exists.
Skipping plasticc_train_metadata.csv.gz, already exists.

Preprocessing the PLAsTiCC dataset...

Preprocessing training metadata...
WARNING:avocado:Overwriting ./data/plasticc_train.h5...
Traceback (most recent call last):
  File "/Users/rs548/anaconda/envs/test/bin/avocado_download_plasticc", line 4, in <module>
    __import__('pkg_resources').run_script('avocado==0.1', 'avocado_download_plasticc')
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/avocado-0.1-py3.7.egg/EGG-INFO/scripts/avocado_download_plasticc", line 174, in <module>
    overwrite=True)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/avocado-0.1-py3.7.egg/avocado/utils.py", line 367, in write_dataframe
    store, key, mode="a", append=append, format="table", data_columns=[chunk_column]
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/pandas/core/generic.py", line 2530, in to_hdf
    pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/pandas/io/pytables.py", line 276, in to_hdf
    path_or_buf, mode=mode, complevel=complevel, complib=complib
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/pandas/io/pytables.py", line 505, in __init__
    self.open(mode=mode, **kwargs)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/pandas/io/pytables.py", line 627, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/Users/rs548/anaconda/envs/test/lib/python3.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1567, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 959, in H5FD_sec2_lock
    unable to lock file, errno = 35, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

**Comment by kboone** [comment] 2019-11-12 21:34
It looks like you ran avocado_download_plasticc one time (which may have been unsuccessful?) and then tried to run it again. Avocado doesn't really support resuming operations right now, and it looks like it is finding a partially preprocessed training dataset (./data/plasticc_train.h5) and then crashing. To fix this, delete the files in ./data (you can keep ./data/plasticc_raw if you would like), and then rerun avocado_download_plasticc.

**Comment by raphaelshirley** [comment] 2019-11-13 12:40
Hi, 

Thanks for the suggestion but that doesn't fix it. It may be a pandas version issue or else a permissions issue working on an external hardrive. I'll let you know if I figure out a fix. I may try tinkering with the code to force a write...

Raphael.

**Comment by kboone** [comment] 2019-11-13 19:13
Ok. Maybe try writing an HDF5 file to that directory using pandas outside of avocado? Here is a toy example to reproduce what avocado is doing internally:

```python
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
store = pd.HDFStore('./test.h5', 'a')
df.to_hdf(store, 'test', mode='a', append=False, format='table', data_columns=['a'])
````

**Comment by raphaelshirley** [comment] 2019-11-14 11:59
Hi, running it directly on my mac fixed it. Hopefully I can move it to the HDD afterwards. Thanks for all you help.

**Comment by kboone** [comment] 2019-11-14 19:01
Ok, sounds like this is either a permissions issue or something in pandas/HDF5 rather than in avocado itself, so I'm going to close the issue for now. Let me know if you run into anything else.

**Closed as completed by kboone** 2019-11-14 19:01 UTC
